project_id = "supiwygxypfqjzoqmlaq"

[functions.domainr-check]
verify_jwt = false

[functions.super-admin-domainr-secret]
verify_jwt = false

[functions.super-admin-whoapi-secret]
verify_jwt = false

[functions.whoapi-check]
verify_jwt = false

[functions.domainduck-check]
verify_jwt = false

[functions.super-admin-domainduck-secret]
verify_jwt = false